### ISSUE TITLE
demo中的一个小错误

### ISSUE THREAD

**Issue by links-zhang** [alipay/private_llm#1]
在demo的prepare_weights.py的98行和103行对输出文件的命名使用是下划线，在readme的终端命令的例子中使用的是-，两者不对应

**Comment by wanglamao** [comment]
感谢提醒，我修正了readme里的错误(https://huggingface.co/wanglamao/PrivateLoRA_GSM8K )。但是我没找到你说的这个错，能详细说说吗？
